name: Build, Test, and Publish

on:
  push:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Set variables
      run: |
        VER=$(cat VERSION)
        echo "VERSION=$VER" >> $GITHUB_ENV
    - name: Update version
      run: |
        sed -i 's/version = .*;/version = \"${{ env.VERSION }}\";/' ./SudokuSolver/Version.cs
        find . -type f -name '*.user.js' | xargs sed -i -E 's/(@version[ \t]*).*/\1${{ env.VERSION }}/'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --nologo --configuration Release --no-restore
    - name: Test
      run: dotnet test --nologo --configuration Release --no-build --verbosity normal
    - name: Publish win-x64
      run: dotnet publish ./SudokuSolverConsole/SudokuSolverConsole.csproj --nologo -c Release -r win-x64 -p:PublishSingleFile=true --self-contained true --no-restore -o publish-win-x64
    - name: Zip win-x64
      uses: papeloto/action-zip@v1
      with:
        files: publish-win-x64/ UserScripts/ Windows/
        dest: SudokuSolver-${{ env.VERSION }}-win-x64.zip
    - name: Publish win10-arm64
      run: dotnet publish ./SudokuSolverConsole/SudokuSolverConsole.csproj --nologo -c Release -r win10-arm64 -p:PublishSingleFile=true --self-contained true --no-restore -o publish-win10-arm64
    - name: Zip win10-arm64
      uses: papeloto/action-zip@v1
      with:
        files: publish-win10-arm64/ UserScripts/ Windows/
        dest: SudokuSolver-${{ env.VERSION }}-win10-arm64.zip
    - name: Publish linux-x64
      run: dotnet publish ./SudokuSolverConsole/SudokuSolverConsole.csproj --nologo -c Release -r linux-x64 -p:PublishSingleFile=true --self-contained true --no-restore -o publish-linux-x64
    - name: tar linux-x64
      run: |
        shopt -s dotglob
        mkdir package-linux-x64
        cp -r ./publish-linux-x64/* ./package-linux-x64
        cp -r ./UserScripts/* ./package-linux-x64
        cp -r ./Linux/* ./package-linux-x64
        cd package-linux-x64
        tar -cpzf ../SudokuSolver-${{ env.VERSION }}-linux-x64.tar.gz *
        cd ..
    - name: Publish osx-x64
      run: dotnet publish ./SudokuSolverConsole/SudokuSolverConsole.csproj --nologo -c Release -r osx-x64 -p:PublishSingleFile=true --self-contained true --no-restore -o publish-osx-x64
    - name: tar osx-x64
      run: |
        shopt -s dotglob
        mkdir package-osx-x64
        cp -r ./publish-osx-x64/* ./package-osx-x64
        cp -r ./UserScripts/* ./package-osx-x64
        cp -r ./OSX/* ./package-osx-x64
        cd package-osx-x64
        tar -cpzf ../SudokuSolver-${{ env.VERSION }}-osx-x64.tar.gz *
        cd ..
    - uses: actions/upload-artifact@v2
      with:
        name: SudokuSolver-${{ env.VERSION }}
        path: |
          SudokuSolver-${{ env.VERSION }}*.zip
          SudokuSolver-${{ env.VERSION }}*.tar.gz
